### ISSUE TITLE
Support for APCu under PHP 7

### ISSUE THREAD

**Issue by Krinkle** [JorgenEvens/php-cache-dashboard#1]
Noticed the following issues needed to be address for this to work on PHP 7 with APCu installed (without the apc-compat setting enabled).

```diff
# 1) PHP Fatal error:  Call to undefined function apc_cache_info()
# 2) PHP Warning:  Invalid argument supplied for foreach()
#     ... because 'cache_list' wasn't defined since 'user' casts to $limited = true
- apc_cache_info('user')
+ apcu_cache_info()

# PHP Fatal error:  Call to undefined function apc_sma_info()
- apc_sma_info(true)
+ apcu_sma_info(true)

- apc_fetch()
+ apcu_fetch()

- apc_delete()
+ apcu_delete()

- new ApcIterator('..')
+ new ApcuIterator('..')

# $type parameter no longer exists
- new ApcIterator('user', get_selector())
+ new ApcuIterator(get_selector())
```

I also recommend changing `var_dump(..fetch..)` to `echo htmlspecialchars( var_export(..fetch.., true) )` as to ensure any HTML characters in the value are rendered as text.

**Comment by JorgenEvens** [comment]
I'll have a look at this tomorrow, would like to keep APC compatibility since I run this on old (~5.3) and new PHP versions, most of which I don't control.

**Comment by JorgenEvens** [comment]
Thanks for reporting this @Krinkle, shouldn't be a problem anymore.

**Comment by Krinkle** [comment]
Thanks! 🌟
