### ISSUE TITLE
Redis and Memcached

### ISSUE THREAD

**Issue by Nirjonadda** [JorgenEvens/php-cache-dashboard#15]
Please can you add support for Redis and Memcached?

**Comment by JorgenEvens** [comment]
I'll look into it, these however are very different from the currently implemented caches in that they require configuration and are not local.

**Comment by burningalchemist** [comment]
Hi Jorgen,

Could you please tell if Redis support can be merged to master? Looking at the available pull request, I think it's fully functional. :)

Kind regards,
Sergei

**Comment by JorgenEvens** [comment]
I'll revisit this over the weekend. Thought there was still something missing, could be wrong.

**Comment by burningalchemist** [comment]
I'm working at the moment on the project using different caches and your dashboard is especially helpful. Thanks! :)

**Comment by JorgenEvens** [comment]
Redis and Memcached support has been released as part of [v1.2.0](https://github.com/JorgenEvens/php-cache-dashboard/releases/tag/v1.2.0).
